### ISSUE TITLE
about msvcp14x_static_part and MFC14X_dynamic_part

### ISSUE THREAD

**Issue by sinfee** [sonyps5201314/msvcr14x#11]
The names of the **msvcp14x_static_part.lib** and **MFC14X_dynamic_part.lib** libraries are the same for both debug and release configurations, which makes it difficult to distinguish between the debug and release versions and causes inconvenience in use. It would be better if the names could be distinguished in the library names.

**Comment by sonyps5201314** [comment]
These are internal intermediate projects. You should use setup.vbs to install this warehouse. Then your VS C++ project will automatically use these link libraries.

**Comment by sinfee** [comment]
Ok, thank you very much for your support
