### ISSUE TITLE
about ntdll library

### ISSUE THREAD

**Issue by sinfee** [sonyps5201314/msvcr14x#12]
In the generated .user.props property file, I only saw the configuration for the IncludePath file, but I did not see the configuration for AdditionalLibraryDirectories in the ntdll.ib file.

<Project DefaultTargets="Build" ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ImportGroup Label="PropertySheets">
	</ImportGroup>
	<PropertyGroup Label="UserMacros"/>
	<PropertyGroup>
		<IncludePath>E:\opensrcs\github\devtools\msvcbuild\ntdll\include;$(IncludePath)</IncludePath>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<Link>
			<AdditionalLibraryDirectories Condition="'$(PlatformToolset)' == 'v143' or '$(PlatformToolset)' == 'v142' or '$(PlatformToolset)' == 'v141' or '$(PlatformToolset)' == 'v141_xp' or '$(PlatformToolset)' == 'v140' or '$(PlatformToolset)' == 'v140_xp'">$(msvcr14x_ROOT)\Release;$(msvcr14x_ROOT)\Debug;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>
	<ItemGroup/>
</Project>

**Comment by sonyps5201314** [comment]
Higher versions of the Windows SDK (such as C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x86) already include ntdll.lib, so this lower version ntdll.lib will not be used by users by default, unless the user manually introduces it.

**Comment by sinfee** [comment]
Ok, thank you very much for your support
